sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 86719858t
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 86719858t
    database: 10
  wechat:
    appid: wxb51a56711dec620d
    secret: 1f529f938eec7da14df6adb62d598869





