sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xxxxxxxxxxx
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
    password: xxxxxxxxxx
    database: x
  wechat:
    appid: xxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxx





